#!/usr/bin/env python3
"""Adds Arabic (ar) localizations to tool/data/word_localizations.json."""

import json
from pathlib import Path

AR_TRANSLATIONS = {
    "pizza": "بيتزا",
    "burger": "برجر",
    "sushi": "سوشي",
    "taco": "تاكو",
    "pasta": "معكرونة",
    "salad": "سلطة",
    "cake": "كعكة",
    "ice_cream": "آيسكريم",
    "popcorn": "فشار",
    "sandwich": "ساندويتش",
    "ramen": "رامن",
    "curry": "كاري",
    "pancake": "فطيرة",
    "steak": "ستيك",
    "dumpling": "زلابية",
    "paella": "بايلا",
    "hot_dog": "هوت دوغ",
    "fries": "بطاطس مقلية",
    "chocolate": "شوكولاتة",
    "cheese": "جبن",
    "apple": "تفاح",
    "banana": "موز",
    "coffee": "قهوة",
    "tea": "شاي",
    "smoothie": "سموذي",
    "bread": "خبز",
    "soup": "حساء",
    "lasagna": "لازانيا",
    "donut": "دونات",
    "omelet": "أومليت",
    "superhero": "بطل خارق",
    "detective": "محقق",
    "space_odyssey": "رحلة فضائية",
    "romantic_comedy": "كوميديا رومانسية",
    "horror": "رعب",
    "animated_movie": "فيلم رسوم متحركة",
    "musical": "مسرحية موسيقية",
    "western": "فيلم غربي",
    "spy_thriller": "تشويق تجسس",
    "time_travel": "سفر عبر الزمن",
    "documentary": "وثائقي",
    "fantasy_epic": "ملحمة خيالية",
    "sports_movie": "فيلم رياضي",
    "courtroom_drama": "دراما محكمة",
    "road_trip": "رحلة برية",
    "martial_arts": "فنون قتالية",
    "monster_movie": "فيلم وحوش",
    "heist": "سرقة",
    "coming_of_age": "بلوغ",
    "silent_film": "فيلم صامت",
    "noir": "فيلم نوار",
    "zombie": "زومبي",
    "pirate": "قرصان",
    "disaster": "كارثة",
    "fairy_tale": "حكاية خيالية",
    "biopic": "سيرة ذاتية",
    "war_movie": "فيلم حرب",
    "alien_invasion": "غزو فضائي",
    "dance_movie": "فيلم رقص",
    "mystery": "غموض",
    "soccer": "كرة قدم",
    "basketball": "كرة سلة",
    "tennis": "تنس",
    "volleyball": "كرة طائرة",
    "swimming": "سباحة",
    "running": "جري",
    "cycling": "دراجات",
    "baseball": "بيسبول",
    "rugby": "رغبي",
    "cricket": "كريكيت",
    "boxing": "ملاكمة",
    "skiing": "تزلج",
    "surfing": "ركوب أمواج",
    "skateboarding": "تزلج على اللوح",
    "golf": "غولف",
    "table_tennis": "تنس طاولة",
    "badminton": "ريشة طائرة",
    "hockey": "هوكي",
    "gymnastics": "جمباز",
    "martial_arts_sport": "فنون قتالية",
    "climbing": "تسلق",
    "archery": "رماية",
    "bowling": "بولينغ",
    "fencing": "مبارزة",
    "rowing": "تجديف",
    "handball": "كرة يد",
    "snowboarding": "تزلج على الجليد",
    "triathlon": "ترياثلون",
    "wrestling": "مصارعة",
    "yoga": "يوغا",
    "guitar": "غيتار",
    "piano": "بيانو",
    "drums": "طبول",
    "violin": "كمان",
    "microphone": "ميكروفون",
    "concert": "حفلة",
    "dj": "دي جي",
    "karaoke": "كاريوكي",
    "jazz": "جاز",
    "rock": "روك",
    "pop_song": "أغنية بوب",
    "opera": "أوبرا",
    "saxophone": "ساكسفون",
    "flute": "ناي",
    "choir": "جوقة",
    "playlist": "قائمة تشغيل",
    "headphones": "سماعات",
    "vinyl": "أسطوانة",
    "rap": "راب",
    "country_music": "موسيقى كانتري",
    "reggae": "ريغي",
    "classical_music": "موسيقى كلاسيكية",
    "festival": "مهرجان",
    "bass": "باس",
    "trumpet": "بوق",
    "songwriter": "مؤلف أغاني",
    "dance_floor": "حلبة رقص",
    "lullaby": "تهويدة",
    "music_video": "فيديو كليب",
    "album": "ألبوم",
    "beach": "شاطئ",
    "mountain": "جبل",
    "airport": "مطار",
    "passport": "جواز سفر",
    "hotel": "فندق",
    "camping": "تخييم",
    "road_trip_travel": "رحلة برية",
    "museum": "متحف",
    "train": "قطار",
    "cruise": "رحلة بحرية",
    "backpack": "حقيبة ظهر",
    "map": "خريطة",
    "souvenir": "تذكار",
    "city_tour": "جولة في المدينة",
    "desert": "صحراء",
    "waterfall": "شلال",
    "island": "جزيرة",
    "hostel": "نزل",
    "safari": "سفاري",
    "temple": "معبد",
    "castle": "قلعة",
    "bus": "حافلة",
    "taxi": "تاكسي",
    "luggage": "أمتعة",
    "market": "سوق",
    "hiking": "تنزه",
    "cave": "كهف",
    "lake": "بحيرة",
    "guidebook": "دليل سفر",
    "sunset": "غروب",
    "dog": "كلب",
    "cat": "قطة",
    "elephant": "فيل",
    "lion": "أسد",
    "tiger": "نمر",
    "giraffe": "زرافة",
    "penguin": "بطريق",
    "dolphin": "دلفين",
    "shark": "قرش",
    "eagle": "نسر",
    "owl": "بومة",
    "horse": "حصان",
    "rabbit": "أرنب",
    "panda": "باندا",
    "kangaroo": "كنغر",
    "monkey": "قرد",
    "snake": "ثعبان",
    "turtle": "سلحفاة",
    "fox": "ثعلب",
    "bear": "دب",
    "wolf": "ذئب",
    "zebra": "حمار وحشي",
    "frog": "ضفدع",
    "whale": "حوت",
    "octopus": "أخطبوط",
    "parrot": "ببغاء",
    "camel": "جمل",
    "koala": "كوالا",
    "bee": "نحلة",
    "butterfly": "فراشة",
}


def main() -> None:
    path = Path("tool/data/word_localizations.json")
    data = json.loads(path.read_text(encoding="utf-8"))

    missing = []
    for word_id, locales in data.items():
        arabic = AR_TRANSLATIONS.get(word_id)
        if arabic is None:
            missing.append(word_id)
            continue
        locales["ar"] = arabic

    if missing:
        raise SystemExit(f"Missing Arabic translations for: {', '.join(missing)}")

    path.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Added Arabic localizations for {len(data)} words.")


if __name__ == "__main__":
    main()
